POST http://localhost:5000/register
Content-type: application/json 

{
    "password": "password",
    "email": "googly567@yaymail.com",
    "shippingAddress": " 489 LOL Street"
}

###

POST http://localhost:5000/login
Content-type: application/json 

{
    "userID": 1,
    "password": "password"
}

###

GET http://localhost:5000/users/1

###
POST http://localhost:5000/products
Content-type: application/json

{
    "productName": "iPhone 25",
    "productDesc": "Smartphone of the Future",
    "productPrice": 150.66
}

###
GET http://localhost:5000/products

###

GET http://localhost:5000/products/1

###
PUT http://localhost:5000/products/3
Content-type: application/json

{
    "updatedName": "Graphing Calculator",
    "updatedDesc": "beep beep DING!",
    "updatedPrice": 30.87
}

###
DELETE http://localhost:5000/products/3 


###

POST http://localhost:5000/orders
Content-type: application/json

{
    "userID": 1,
    "products": [{
        "productID": 1,
        "quantity": 1,
        "price": 45.99
    },
    {
        "productID": 2,
        "quantity": 2,
        "price": 51.00
    }],

    "paymentDetails": "Yolo Card 67896"
}