POST http://localhost:5000/register
Content-type: application/json 

{
    "password": "password",
    "email": "googly567@yaymail.com",
    "shippingAddress": " 489 LOL Street"
}

###

POST http://localhost:5000/login
Content-type: application/json 

{
    "userID": 1,
    "password": "password"
}

###

GET http://localhost:5000/users/1

###
POST http://localhost:5000/products
Content-type: application/json

{
    "productName": "iPhone 25",
    "productDesc": "Smartphone of the Future",
    "productPrice": 150.66
}

###
GET http://localhost:5000/products

###

GET http://localhost:5000/products/1
